# 389. Find the Difference
# You are given two strings s and t.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Return the letter that was added to t.

 

# Example 1:

# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added.
# Example 2:

# Input: s = "", t = "y"
# Output: "y"
 

# Constraints:

# 0 <= s.length <= 1000
# t.length == s.length + 1
# s and t consist of lowercase English letters.

#CODE

def find_diff(s,t):
    a=0
    for i in s+t:
        a^=ord(i)
    return chr(a)
s=input("enter string1")
t=input("enter string2")
print(find_diff(s,t))